### PR TITLE
Release v0.3.15

### PR DESCRIPTION
**Pull request by angrybayblade**

### CODE REVIEW

**Review by sohamganatra — APPROVED** [review]

**Comment by utkarsh-dixit** [comment]
### PR Changes Summary 
- **Objective**: This pull request aims to update the versions of multiple Python plugin packages.
- **Changes**:
  - Bumped versions for several plugin packages from `0.3.14` to `0.3.15` and updated their dependencies.
  
### Type
- **Type**: Feature

### Important Changed Files
- `python/plugins/autogen/setup.py`
- `python/plugins/claude/setup.py`
- `python/plugins/crew_ai/setup.py`
- `python/plugins/griptape/setup.py`
- `python/plugins/julep/setup.py`
- `python/plugins/langchain/setup.py`
- `python/plugins/llamaindex/setup.py`
- `python/plugins/lyzr/setup.py`
- `python/plugins/openai/setup.py`
- `python/setup.py`

**Comment by himanshu-dixit** [comment]
### PR Summary

**Describe the changes of this PR and its objective:**
The primary objective of this PR is to bump the version of various `composio` packages and plugins from `0.3.14` to `0.3.15`. This version update likely includes various improvements and bug fixes, but the specific changes to the core logic or added features are not detailed in the files provided.

**Categorize this PR:**
- **Type:** Feature

**Important change files which contain the major logical changes of this PR:**
1. `python/plugins/autogen/setup.py`
2. `python/plugins/claude/setup.py`
3. `python/plugins/crew_ai/setup.py`
4. `python/plugins/griptape/setup.py`
5. `python/plugins/julep/setup.py`
6. `python/plugins/langchain/setup.py`
7. `python/plugins/llamaindex/setup.py`
8. `python/plugins/lyzr/setup.py`
9. `python/plugins/openai/setup.py`
10. `python/setup.py`

### Changes Summary

This feature PR updates the version numbers of various `composio` packages from `0.3.14` to `0.3.15` in the setup files across several plugins. The changes are as follows:

- **Modified Files:**
  - `python/plugins/autogen/setup.py`
  - `python/plugins/claude/setup.py`
  - `python/plugins/crew_ai/setup.py`
  - `python/plugins/griptape/setup.py`
  - `python/plugins/julep/setup.py`
  - `python/plugins/langchain/setup.py`
  - `python/plugins/llamaindex/setup.py`
  - `python/plugins/lyzr/setup.py`
  - `python/plugins/openai/setup.py`
  - `python/setup.py`

- **Changes:**
  - Updated version from `0.3.14` to `0.3.15`.
  - Adjusted the `install_requires` field to reflect the new version dependency.

**Comment by himanshu-dixit** [comment]
### Changes of This PR and its Objective
This Pull Request (PR) updates various Python plugins and the core package of the `Composio` repository to version `0.3.15`. The objective of this PR is to align all relevant dependencies within the plugins with the new core package version, ensuring consistency and potentially introducing new improvements or bug fixes that come with the updated core version.

### Categorization
This PR falls into the **Feature** category since it includes a version bump that may introduce new features or improvements.

### Important Change Files
The main files that contain the significant logical changes in this PR are:
- `python/plugins/autogen/setup.py`
- `python/plugins/claude/setup.py`
- `python/plugins/crew_ai/setup.py`
- `python/plugins/griptape/setup.py`
- `python/plugins/julep/setup.py`
- `python/plugins/langchain/setup.py`
- `python/plugins/llamaindex/setup.py`
- `python/plugins/lyzr/setup.py`
- `python/plugins/openai/setup.py`
- `python/setup.py`

These files have been modified to update their respective versions from `0.3.14` to `0.3.15`.

**Comment by himanshu-dixit** [comment]
### Changes Summary:

#### Describe the Changes and Objective:
This PR aims to bump the version of multiple components in the repository to `v0.3.15` from the previous version `v0.3.14`. The objective is to update the version dependencies across various plugins to ensure consistency and possibly include updates or bug fixes provided in the newer versions of the components.

#### Categorize this PR:
- **Type:** Feature

#### Important Changed Files:
- `python/plugins/autogen/setup.py`
- `python/plugins/claude/setup.py`
- `python/plugins/crew_ai/setup.py`
- `python/plugins/griptape/setup.py`
- `python/plugins/julep/setup.py`
- `python/plugins/langchain/setup.py`
- `python/plugins/llamaindex/setup.py`
- `python/plugins/lyzr/setup.py`
- `python/plugins/openai/setup.py`
- `python/setup.py`

### Comments on this PR:
This PR includes updates to the `setup.py` files for multiple Python plugins and the core package. Each file had changes to bump both the version number of the plugin and the `composio_core` dependency to `v0.3.15`.

Summarizing the changes in each file:
- Updated the `version` field to `0.3.15`.
- Updated the `install_requires` field to ensure `composio_core==0.3.15`.

Let's ensure that all dependencies are correctly updated and that no additional changes are accidentally included.

**Pull request merged**
